swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "0.9.0"
  title: "WSO2 Identity Server Rest API - Recovery"
  description: |
    This document specifies a **RESTful API** for WSO2 **Identity Server** .

    It is written with [swagger 2](http://swagger.io/).

  contact:
    name: "WSO2"
    url: "http://wso2.com/products/identity-server/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
  - https

# The domain of the API.
# This is configured by the system administrator during deployment.
# The given host is just an example.
host: apis.is.com

# The base path of the API.
# Will be prefixed to all paths.
# if the tenant domain is carbon.super basepath can be /api/identity/recovery/v0.9 like this too.
basePath: /t/{tenant-domain}/api/identity/recovery/v0.9

# The following media types can be passed as input in message bodies of the API.
# The actual media type must be specified in the Content-Type header field of the request.
# The default is json, i.e. the Content-Type header is not needed to
# be set, but supporting it serves extensibility.
consumes:
  - application/json

# The following media types may be passed as output in message bodies of the API.
# The media type(s) consumable by the requestor is specified in the Accept header field
# of the corresponding request. 
# The actual media type returned will be specfied in the Content-Type header field 
# of the response.
# The default of the Accept header is JSON, i.e., it is not needed to
# set the value, but supporting it serves extensibility.
produces:
  - application/json
paths:
  # The endpoint that is used to send recovery notifications.
  /recover-password:
    post:
      description: |
        This API is used to send password recovery confirmation over defined channels like email/sms.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"user": {"username": "isura","realm": "ENGINEERING","tenant-domain":"carbon.super"},"properties": []}' "https://localhost:9443/api/identity/recovery/v0.9/recover-password?type=email¬ify=true"

      x-wso2-response: |
        "HTTP/1.1 202 Accepted"
      summary: |
        Send Recovery Notification

      # These are the post parameters:
      parameters:
        -
          name: RecoveryInitiatingRequest
          in: body
          description: Optional property parameters can be sent via email based on the email template.
          required: true
          schema:
            $ref: '#/definitions/RecoveryInitiatingRequest'
        -
          name: type
          in: query
          description: Notification Type
          required: false
          type: string

        -
          name: notify
          in: query
          description: If notify=true, notifications will be internally managed.
          required: false
          type: boolean

      responses:
        202:
          description: Successful response
          schema:
            title: key
            type: string
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Password Recovery
        - Notification

    # The endpoint that is used to reset the user password.
  /set-password:

    post:
      description: |
        This API is used to reset user password using the confirmation key recieved through the recovery process. Need to input `key` and the new `password`.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"key": "5c765a47-6764-4048-b5cf-55864cb654c0", "password": "P@ssW0rd","properties": []}' "https://localhost:9443/api/identity/recovery/v0.9/set-password"

      x-wso2-response: |
        "HTTP/1.1 202 ACCEPTED"
      summary: |
        Update Password

      parameters:
        -
          name: ResetPasswordRequest
          in: body
          description: Key, password, and optional metadata properties.
          required: true
          schema:
            $ref: '#/definitions/ResetPasswordRequest'

      responses:
        202:
          description: Successful response
          schema:
            $ref: '#/definitions/User'

        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        412:
          description: Precondition Failed
          schema:
            $ref: '#/definitions/RetryError'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Password Recovery
        - Notification

  /validate-code:
    post:
      description: |
        This API is used to validate confirmation codes sent in account recovery scenarios and self signup. You need to input the confirmation "code" and recovery "step" as parameters.
      x-wso2-request: |
        curl -k -v -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{ "code": "84325529-8aa7-4851-8751-5980a7f2d9f7","step": "UPDATE_PASSWORD","properties": []}' "https://localhost:9443/api/identity/recovery/v0.9/validate-code"

      x-wso2-response: |
        "HTTP/1.1 202 Accepted"

      summary: |
        Validate Confirmation Code

      # These are the post parameters:
      parameters:
        -
          name: CodeValidationRequest
          in: body
          description: Code, recovery step, and optional parameters. For recovery steps, you can use values from "UPDATE_PASSWORD","CONFIRM_SIGN_UP","VALIDATE_CHALLENGE_QUESTION", and "VALIDATE_ALL_CHALLENGE_QUESTION" four categories according to the recovery scenario you want to validate the code.
          required: true
          schema:
            $ref: '#/definitions/CodeValidationRequest'
      responses:
        202:
          description: Accepted
          schema:
            $ref: '#/definitions/User'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Password Recovery

  /recover-username/:
    post:
      description: |
        This API can be used to recover a forgotten username.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '[{"uri": "http://wso2.org/claims/givenname","value": "isura"},{"uri": "http://wso2.org/claims/emailaddress", "value": "isuradil@email.com"},{"uri": "http://wso2.org/claims/lastname","value": "karunaratne" }]' "https://localhost:9443/api/identity/recovery/v0.9/recover-username/"

      x-wso2-response: |
        "HTTP/1.1 202 Accepted"

      summary: |
        Recover username

      parameters:
        -
          name: Claim
          in: body
          description: User answers for recovery claims.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/UserClaim'
        -
          name: tenant-domain
          in: query
          description: Tenant Domain that the user belongs to. Default `carbon.super`
          required: false
          type: string
        -
          name: notify
          in: query
          description:  If notify=true, notifications will be internally managed.
          required: false
          type: boolean

      responses:
        202:
          description: Successful response
        204:
          description: No valid user found for given data.

        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Username Recovery
        - Notification

  /claims:
    get:
      description: |
        return the recovery supported claims in the given tenant.
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/recovery/v0.9/claims?tenant-domain=carbon.super"

      x-wso2-response: |
        [{"uri":"http://wso2.org/claims/mobile","value":null,"description":"Mobile","display-name":"Mobile","dialect":"http://wso2.org/claims","required":false,"readOnly":false},{"uri":"http://wso2.org/claims/role","value":null,"description":"Role","display-name":"Role","dialect":"http://wso2.org/claims","required":false,"readOnly":true},{"uri":"http://wso2.org/claims/givenname","value":null,"description":"First Name","display-name":"First Name","dialect":"http://wso2.org/claims","required":true,"readOnly":false},{"uri":"http://wso2.org/claims/organization","value":null,"description":"Organization","display-name":"Organization","dialect":"http://wso2.org/claims","required":false,"readOnly":false},{"uri":"http://wso2.org/claims/im","value":null,"description":"IM","display-name":"IM","dialect":"http://wso2.org/claims","required":false,"readOnly":false},{"uri":"http://wso2.org/claims/lastname","value":null,"description":"Last Name","display-name":"Last Name","dialect":"http://wso2.org/claims","required":true,"readOnly":false},{"uri":"http://wso2.org/claims/telephone","value":null,"description":"Telephone","display-name":"Telephone","dialect":"http://wso2.org/claims","required":false,"readOnly":false},{"uri":"http://wso2.org/claims/country","value":null,"description":"Country","display-name":"Country","dialect":"http://wso2.org/claims","required":false,"readOnly":false},{"uri":"http://wso2.org/claims/emailaddress","value":null,"description":"Email Address","display-name":"Email","dialect":"http://wso2.org/claims","required":true,"readOnly":false},{"uri":"http://wso2.org/claims/url","value":null,"description":"URL","display-name":"URL","dialect":"http://wso2.org/claims","required":false,"readOnly":false}]

      summary: |
        Get Supported Claims

      parameters:
        -
          name: tenant-domain
          in: query
          description: tenant domain. Default `carbon.super`
          required: false
          type: string

        - name: profile-name
          in: query
          description: profile name`
          required: false
          type: string

      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Claim'

        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Username Recovery

  /captcha:
    get:
      description: |
        return the reCaptcha information if its supported for the given tenant.
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"  "https://localhost:9443/api/identity/recovery/v0.9/captcha?tenant-domain=carbon.super&captcha-type=ReCaptcha&recovery-type=username-recovery"
      x-wso2-response: |
        {"reCaptchaEnabled":true,"reCaptchaKey":"6LctLW4UAAAA5YWxy93f7yBQlzMh_RdkmUxd-J","reCaptchaAPI":"https://www.google.com/recaptcha/api.js"}
      operationId: getCaptcha

      summary: |
        Get Captcha

      parameters:
        -
          name: tenant-domain
          in: query
          description: tenant domain. Default `carbon.super`
          required: false
          type: string

        -
          name: captcha-type
          in: query
          description: type of captcha
          required: true
          type: string

        -
          name: recovery-type
          in: query
          description: username recovery or password recovery
          required: true
          type: string

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ReCaptchaProperties'

        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Password Recovery
        - Username Recovery

    post:
      description: |
        return true or false after verify the captcha response.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"token": "xsfwewfcavfrwafrawva"}' "https://localhost:9443/api/identity/recovery/v0.9/captcha?tenant-domain=carbon.super&captcha-type=ReCaptcha"

      x-wso2-response: |
        {"success":true}

      operationId: verifyCaptcha

      summary: |
        Verify Captcha

      parameters:
        -
          name: reCaptcha-response
          in: body
          description: recaptcha response from google.
          required: true
          schema:
            $ref: '#/definitions/ReCaptchaResponseToken'

        -
          name: tenant-domain
          in: query
          description: tenant domain. Default `carbon.super`
          required: false
          type: string

        -
          name: captcha-type
          in: query
          description: type of captcha
          required: true
          type: string

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ReCaptchaVerificationResponse'

        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
        - Password Recovery
        - Username Recovery

definitions:
  #-----------------------------------------------------
  # The User Object
  #-----------------------------------------------------
  User:
    type: object
    properties:
      username:
        type: string
      realm:
        type: string
      tenant-domain:
        type: string
  #-----------------------------------------------------
  # The Credential object
  #-----------------------------------------------------
  ResetPasswordRequest:
    type: object
    properties:
      key:
        type: string
      password:
        type: string
      properties:
        type: array
        items:
          $ref: '#/definitions/Property'

  #-----------------------------------------------------
  # The Error Response object
  #-----------------------------------------------------
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string

  #-----------------------------------------------------
  # The Error Response object
  #-----------------------------------------------------
  RetryError:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string
      key:
        type: string
  #-----------------------------------------------------
  # The Property object
  #-----------------------------------------------------
  Property:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
  #-----------------------------------------------------
  # Claim object
  #-----------------------------------------------------
  Claim:
    type: object
    properties:
      uri:
        type: string
      value:
        type: string
      description:
        type: string
      display-name  :
        type: string
      dialect:
        type: string
      validation-regex:
        type: string
      required:
        type: boolean
      read-only:
        type: boolean
      display-order:
        type: string
  #-----------------------------------------------------
  # Link object
  #-----------------------------------------------------
  Link:
    type: object
    properties:
      rel:
        type: string
      uri:
        type: string

  #-----------------------------------------------------
  # User Claim object
  #-----------------------------------------------------
  UserClaim:
    type: object
    properties:
      uri:
        type: string
      value:
        type: string
  #-----------------------------------------------------

  #-----------------------------------------------------
  # The CodeValidationRequest object
  #-----------------------------------------------------
  CodeValidationRequest:
    type: object
    properties:
      code:
        type: string
      step:
        type: string
      properties:
        type: array
        items:
          $ref: '#/definitions/Property'
  #-----------------------------------------------------

  #-----------------------------------------------------
  # ReCaptcha Response Token object
  #-----------------------------------------------------
  ReCaptchaResponseToken:
    type: object
    properties:
      token:
        type: string
  #-----------------------------------------------------

  #-----------------------------------------------------
  # ReCaptcha verification response object
  #-----------------------------------------------------
  ReCaptchaVerificationResponse:
    type: object
    properties:
      success:
        type: boolean
  #-----------------------------------------------------

  #-----------------------------------------------------
  # ReCaptcha Properties object
  #-----------------------------------------------------
  ReCaptchaProperties:
    type: object
    properties:
      reCaptchaEnabled:
        type: boolean
      reCaptchaType:
        type: string
      reCaptchaKey:
        type: string
      reCaptchaAPI:
        type: string
#-----------------------------------------------------


